export const apiUrl = {
    baseImageUrl: 'http://smegroup.org/client/adminBook/',
    userLogin: 'api/login',
    signupUrl: 'api/studentRegister',
    getModuleUrl: 'api/moduleList',
    forgotPasswordUrl: 'api/ForgotPassword',
    createModuleUrl: 'api/moduleCreate',
    updateModuleUrl: 'api/moduleEdit' ,
    deleteModuleUrl: 'api/moduleDelete',
    getCategoryUrl: 'api/categoryList',
    createCategoryUrl: 'api/categoryCreate',
    createSubCategoryUrl: 'api/subcategoryCreate',
    getSubCategoryUrl: 'api/subcategoryList',
    editCategoryUrl: 'api/categoryEdit',
    deleteCategoryUrl: 'api/categoryDelete',
    editSubCategoryUrl: 'api/subcategoryEdit',
    deleteSubCategoryUrl: 'api/subcategoryDelete',  
    createTestUrl: 'api/examCreate',
    testListUrl: 'api/examList',
    questionListUrl: 'api/quesAnsList',
    addQuestionUrl: 'api/quesAnsCreate',
    getTestDetailUrl: 'api/examDetails',
    updateTestUrl: 'api/examEdit',
    feedCreateUrl: 'api/feedsCreate',
    feedDeleteUrl: 'api/feedsDelete',
    feedEditUrl: 'api/feedsEdit',
    feedListUrl: 'api/feedsList',
    feedShareDeleteUrl: 'api/feedsShareDelete',
    feedShareUrl: 'api/feedsShare',
    feedLikeUrl: 'api/feedsLike'
}
